# Generated by Django 3.1.1 on 2020-09-17 10:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=45)),
            ],
        ),
        migrations.CreateModel(
            name='Main_category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('main_category', models.CharField(max_length=45)),
            ],
        ),
        migrations.CreateModel(
            name='Product_group',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_group_name', models.CharField(max_length=45, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Sub_category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sub_category', models.CharField(max_length=45)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Product.category')),
            ],
        ),
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=45)),
                ('price', models.IntegerField(default=0)),
                ('point', models.IntegerField(default=0)),
                ('thumbnail', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('info', models.TextField()),
                ('notice', models.TextField()),
                ('sale_price', models.IntegerField(null=True)),
                ('hover_image', models.BooleanField(default=False, null=True)),
                ('detail_image_url', models.TextField()),
                ('sub_text', models.CharField(max_length=45, null=True)),
                ('product_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Product.product_group')),
                ('sub_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Product.sub_category')),
            ],
        ),
        migrations.CreateModel(
            name='Product_related',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product', to='Product.products')),
                ('related_product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='related_product', to='Product.products')),
            ],
        ),
        migrations.CreateModel(
            name='Product_category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.ManyToManyField(to='Product.Category')),
                ('product', models.ManyToManyField(to='Product.Products')),
            ],
        ),
        migrations.AddField(
            model_name='category',
            name='main_category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Product.main_category'),
        ),
    ]
