# Generated by Django 3.1 on 2020-09-18 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='hover_image',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
