# Generated by Django 3.1.1 on 2020-09-20 06:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0002_auto_20200918_1057'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='DetailImageUrl',
            new_name='DetailImage',
        ),
        migrations.AddField(
            model_name='productgroup',
            name='subcategory',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Product.subcategory'),
        ),
    ]
