# Generated by Django 3.1.1 on 2020-09-23 06:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0002_auto_20200918_1057'),
    ]

    operations = [
        migrations.AddField(
            model_name='productgroup',
            name='sub_category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Product.subcategory'),
        ),
    ]
