# Generated by Django 3.1.1 on 2020-09-17 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userid', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=100)),
                ('user_name', models.CharField(max_length=50)),
                ('address', models.CharField(max_length=100)),
                ('telephone', models.IntegerField()),
                ('phonenumber', models.IntegerField()),
                ('email', models.CharField(max_length=100)),
                ('sex', models.CharField(choices=[('M', '남자'), ('F', '여자')], max_length=1)),
                ('birthday', models.DateField(choices=[('S', '양력'), ('L', '음력')], max_length=1, null=True)),
                ('area', models.CharField(choices=[('1', '경기'), ('2', '서울'), ('3', '인천'), ('4', '강원'), ('5', '충남'), ('6', '충북'), ('7', '대전'), ('8', '경북'), ('9', '경남'), ('10', '대구'), ('11', '부산'), ('12', '울산'), ('13', '전북'), ('14', '전남'), ('15', '광주'), ('16', '제주'), ('17', '해외')], max_length=2)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'user',
            },
        ),
    ]
